version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - epub

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .