codecov:
  require_ci_to_pass: yes
  branch: dev-2.x

ignore:
  - "glQiwiApi/ext"
  - "glQiwiApi/utils/mypy_hacks.py"
  - "glQiwiApi/utils/compat.py"
  - "glQiwiApi/utils/payload.py"
  - "glQiwiApi/qiwi/clients/wrapper.py"
  - "glQiwiApi/utils/deprecated.py"
  - "glQiwiApi/utils/date_conversion.py"
  - "glQiwiApi/utils/synchronous.py"
  - "glQiwiApi/core/cache"

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  branches:
    - dev-2.x
  after_n_builds: 6