codecov:
  require_ci_to_pass: yes
  branch: dev-1.x

ignore:
  - "glQiwiApi/ext"
  - "glQiwiApi/yoo_money"

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  branches:
    - dev-1.x
  after_n_builds: 6