# Copied from https://github.com/pallets/flask/blob/main/.github/workflows/lock.yaml

# This does not automatically close "stale" issues. Instead, it locks closed issues after 3 weeks of no activity.
# If there's a new issue related to an old one, we've found it's much easier to work on as a new issue.

name: 'Lock threads'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v3
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: 21
          pr-inactive-days: 21
