name: Publish to the Pypi

on:
  push:
    tags:
      - '2.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.1
          virtualenvs-create: false
          installer-parallel: true

      - name: Build
        run: |
          poetry build
      - name: Try install wheel
        run: |
          pip install -U virtualenv
          mkdir -p try_install
          cd try_install
          virtualenv venv
          venv/bin/pip install ../dist/glQiwiApi-*.whl
          venv/bin/python -c "import glQiwiApi; print(glQiwiApi.__version__)"
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish
    needs: build
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
