name: Publish to pypy

on:
  push:
    tags:
      - '1.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -U pip virtualenv poetry
          poetry config virtualenvs.create false
      - name: Build
        run: |
          poetry build
      - name: Try install wheel
        run: |
          mkdir -p try_install
          cd try_install
          virtualenv venv
          venv/bin/pip install ../dist/glQiwiApi-*.whl
          venv/bin/python -c "import glQiwiApi; print(glQiwiApi.__version__)"
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish
    needs: build
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}